lang: zh-CN
title: Mambo723 Blog
description: "拔剑舞中庭，浩歌振林峦；丈夫意如此，不学腐儒酸。"
show_downloads: false
google_analytics: false

github:
  is_project_page: false
  repository_url: ""
  repository_name: ""
  project_tagline: ""
  zip_url: ""
  tar_url: ""
  owner_url: ""
  build_revision: ""

gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: 90d619dd06c206c80f71                            #生成的clientID
  clientSecret: 1071184e9183c7904e4e9b10c03567d1aacae817    #生成的clientSecret
  repo: mambo723.github.io    #仓库名称
  owner: mambo723    #github用户名
  admin: mambo723
  distractionFreeMode: true #是否启用类似FB的阴影遮罩


theme: jekyll-theme-slate